# packages/duckduckgo/pyproject.toml
[project]
name = "aihive-tools-duckduckgo"
version = "0.0.4"
description = "DuckDuckGo tools for AIHive framework."
requires-python = ">=3.7"
readme = "../../README.md"
authors = [
    { name = "Jacob Weiss", email = "jaweiss2305@gmail.com" }
]

dependencies = [
    "duckduckgo-search",
]

[project.urls]
homepage = "https://github.com/jacobweiss2305/aihive-tools"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["aihive_tools", "aihive_tools.duckduckgo*"]
where = ["../../"]

[tool.setuptools.package-data]
aihive_tools = ["py.typed"]